viewport fixes for world overview page
koiosonline/app.koios.world pull request #117
Opened 2021-09-26 18:24 UTC by superstephan1

- Made the world overview buttons a bit more responsive. Still not perfect but it's an improvement worth releasing.
- Deleted unused comments and stuff.
- The team component stuff was already pushed earlier so not sure why it's commited into this aswell lol. You can ignore that cause the code is already live on dev.

2021-09-28 15:29 UTC, Rowin206 requested changes

2021-09-28 15:29 UTC, Rowin206 commented on src/assets/css/pages/_WorldOverview.scss
> +  //background-size: cover;
There are some comments

2021-09-29 09:29 UTC, superstephan1 commented on src/assets/css/pages/_WorldOverview.scss
> +  //background-size: cover;
My bad thanks!

2021-09-29 10:39 UTC, Rowin206 approved these changes

2021-09-29 10:39 UTC, merged